config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'index#index'
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check
  devise_for :users, controllers: { sessions: 'users/sessions' }
  namespace :admin do
    root 'sessions#new'
    resources :sessions
    resources :tickets
  end
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  validates :movie_name, presence: { message: "电影名称不能为空" }
  validates :show_time, presence: { message: "放映时间不能为空" }
  validates :duration, presence: { message: "时长不能为空" }
  validates :stock, numericality: { only_integer: true, message: "库存必须是整数" },
            if: proc { |ticket| ticket.price.blank? }
  validates :stock, presence: { message: "库存不能为空" }
  validates :price, numericality: {  message: "价格必须是数字" },
            if: proc { |ticket| ticket.price.blank? }
  validates :price, presence: { message: "价格不能为空" }
  validates :status, presence: { message: "状态不能为空" }
  validates :status, inclusion: { in: %w[on off], message: "状态必须是上架或下架" }
  validates :description, presence: { message: "描述不能为空" }
  before_create :set_uuid
  has_one_attached :image
  module Status
    On = 'on'
    Off = 'off'
  end
  def small_image
    image.variant(resize: "60x60^").processed
  end

  def middle_image
    image.variant(resize: "200x200^").processed
  end

  def big_image
    image.variant(resize: "960x").processed
  end
  private
  def set_uuid
    self.uuid = SecureRandom.uuid
  end
end

app/controllers/admin/tickets_controller.rb
class Admin::TicketsController < Admin::BaseController
  def index
    @tickets = Ticket.page(params[:page] || 1).per(params[:per_page] || 10)
                     .order("id desc")
  end

  def new
    @ticket = Ticket.new
  end
  def create
    @ticket = Ticket.new(params.require(:ticket).permit!)
    if @ticket.save
      flash[:notice] = "Ticket created successfully"
      redirect_to admin_tickets_path
    else
      render action: :new
    end

  end

  def edit
    @ticket = Ticket.find(params[:id])
    render action: :new

  end

  def update
  @ticket = Ticket.find(params[:id])
  @ticket.attributes = params.require(:ticket).permit!
  if @ticket.save
    flash[:notice] = "Ticket updated successfully"
    redirect_to admin_tickets_path
  else
    render action: :new
  end
  end

  def destroy
    @ticket = Ticket.find(params[:id])
    if @ticket.destroy
      flash[:notice] = "Ticket deleted successfully"
      redirect_to admin_tickets_path
    else
      flash[:error] = "Ticket could not be deleted"
      redirect_to :back
    end
  end
end

app/helpers/admin/tickets_helper.rb
module Admin::TicketsHelper
end

app/views/admin/tickets/index.html.erb
<div>
  <div class="pull-right">
    <%= link_to "新建电影", new_admin_ticket_path, class: "btn btn-primary" %>
  </div>

  <h1>
    电影(<%= @tickets.total_count %>)
  </h1>
</div>

<div>
  <table class="table table-striped">
    <tr>
      <th>id</th>
      <th>电影名称</th>
      <th>上映时间</th>
      <th>时长</th>
      <th>库存</th>
      <th>价格</th>
      <th>状态</th>
      <th>描述</th>
      <th>创建时间</th>
      <th>更新时间</th>

    </tr>

    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.id %></td>
        <td><%= ticket.movie_name %></td>
        <td><%= ticket.show_time %></td>
        <td><%= ticket.duration %></td>
        <td><%= ticket.stock %></td>
        <td><%= ticket.price %></td>
        <td><%= ticket.status %></td>
        <td><%= ticket.description %></td>
        <td><%= ticket.created_at %></td>
        <td><%= ticket.updated_at %></td>

        <td align="right">
          <%= link_to "编辑", edit_admin_ticket_path(ticket) %>
          <%= link_to "删除", admin_ticket_path(ticket), method: :delete, 'data-confirm': "确认删除吗?" %>
        </td>
      </tr>
    <% end -%>
  </table>

  <%= paginate @tickets %>
</div>

app/views/admin/tickets/new.html.erb
<div>
  <h1><%= @ticket.new_record? ? "新建" : "修改 ##{params[:id]}" %></h1>
</div>

<div class="form-body">
  <%= form_for @ticket,
               url: (@ticket.new_record? ? admin_tickets_path : admin_ticket_path(@ticket)),
               method: (@ticket.new_record? ? 'post' : 'put'),
               html: { class: 'form-horizontal' } do |f| %>

    <% unless @ticket.errors.blank? %>
      <div class="alert alert-danger">
        <ul class="list-unstyled">
          <% @ticket.errors.messages.values.flatten.each do |error| %>
            <li><i class="fa fa-exclamation-circle"></i> <%= error %></li>
          <% end -%>
        </ul>
      </div>
    <% end -%>
<!--    create_table "tickets", force: :cascade do |t|-->
<!--    t.string "movie_name"-->
<!--    t.datetime "show_time"-->
<!--    t.integer "duration"-->
<!--    t.integer "stock"-->
<!--    t.integer "price"-->
<!--    t.string "status"-->
<!--    t.string "uuid"-->
<!--    t.text "description"-->
<!--    t.datetime "created_at", null: false-->
<!--    t.datetime "updated_at", null: false-->
<!--    end-->

    <div class="form-group">
      <label for="movie_name" class="col-sm-2 control-label">电影名称*:</label>
      <div class="col-sm-5">
        <%= f.text_field :movie_name, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <label for="show_time" class="col-sm-2 control-label">上映时间*:</label>
      <div class="col-sm-5">
        <%= f.text_field :show_time, class: "form-control", value: f.object.show_time || Time.current.strftime('%Y-%m-%d %H:%M:%S') %>
      </div>
    </div>

    <div class="form-group">
      <label for="duration" class="col-sm-2 control-label">时长*:</label>
      <div class="col-sm-5">
        <%= f.text_field :duration, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <label for="stock" class="col-sm-2 control-label">库存*:</label>
      <div class="col-sm-5">
        <%= f.text_field :stock, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <label for="price" class="col-sm-2 control-label">价格*:</label>
      <div class="col-sm-5">
        <%= f.text_field :price, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <label for="description" class="col-sm-2 control-label">描述*:</label>
      <div class="col-sm-5">
        <%= f.text_area :description, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <label for="movie_name" class="col-sm-2 control-label">上下架状态:*</label>
      <div class="col-sm-5">
        <select name="ticket[status]">
          <% [[Ticket::Status::On, '上架'], [Ticket::Status::Off, '下架']].each do |row| %>
            <option value="<%= row.first %>" <%= 'selected' if @ticket.status == row.first %>><%= row.last %></option>
          <% end -%>
        </select>
      </div>
    </div>


    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-8">
        <%= f.submit (@ticket.new_record? ? "新建" : "编辑"), class: "btn btn-default" %>
      </div>
    </div>
  <% end -%>
</div>