config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'index#index'
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check
  devise_for :users, controllers: { sessions: 'users/sessions' }
  namespace :admin do
    root 'sessions#new'
    resources :sessions
    resources :tickets
  end
  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/admin/layouts/_menu.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= admin_root_path %>">管理平台</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="<%= admin_root_path %>">Home <span class="sr-only">(current)</span></a></li>
        <li><a href="<%= admin_tickets_path %>">电影票管理</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "退出", destroy_user_session_path, method: :delete %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/admin/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>管理平台</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'admin', media: 'all' %>
  <%= yield :stylesheets %>
</head>

<body>
<%= render 'admin/layouts/menu' %>
<div class="container">
  <% unless flash[:notice].blank? %>
    <div class="alert alert-info"><%= flash[:notice] %></div>
  <% end -%>

  <%= yield %>
</div>

<%= javascript_include_tag 'admin' %>
<%= yield :javascripts %>
</body>
</html>